name: Create Pull Request from develop to QA

on:
  push:
    branches:
      - develop

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create pull request from develop to QA
      uses: devops-infra/action-pull-request@v0.5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        title: Automatic pull request
        source_branch: develop
        target_branch: QA
