name: Auto PR

on:  
  push:
   branches:
    -nayana

jobs:
  Auto-pr-create:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: pr
      uses: desbravacloud/action-create-pull-requests@v1
      with:
       origin-branch: 'develop'
       target-branch: 'main'
       custom-title: 'PR created'
       custom-body: 'Please, check thease changes'
