name: Automatically create/update pull request from QA to Development

on:
  push:
 
jobs:
  create_pr_qa_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Git configuration
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "nayana@devtools.in"
      - name: Create or update pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create  --source UAT --head develop --title "The bug is fixed" --body "Everything works again"
