name: Create Pull Request on Push

on:
  push:
    branches:
      - 'test'  # Replace 'main' with the branch you want to target

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const title = 'created by bot';
            const branchName = 'test';
            const baseBranch = 'develop';
            const body = 'Your PR Description1';

            const response = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              head: branchName,
              base: baseBranch,
              body: body,
            });
            console.log(`Created PR: ${response.data.html_url}`);

        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
