on:
  push:
    branches:
      - develop

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        
        with:
          script: |
            curl -L \
               -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer 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" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/github-devtools-2022/shiva-repo/pulls \
               -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"octocat:new-feature","base":"master"}'
