name: Create PR Comment on Push

on:
  push:
    branches:
      - main  # Replace 'main' with the branch you want to target

jobs:
  create-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create PR Comment
        uses: actions/github-script@v6
        with:
          script: |
            if (github.context.payload.pull_request) {
              github.rest.pulls.createComment({
                pull_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '👋 Thanks for your pull request!'
              });
            } else {
              echo "No pull request found; skipping comment creation."
            }
