name: Automatically

on:  
  pull_request:

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Terrafrom init
      if: github.event_name == 'pull_request' 
#&& github.ref == 'refs/heads/develop' 
    - run: echo "Terraform init"
   
    - name: Terraform apply
     #if: ${{ github.head_ref	== 'refs/heads/main'|| github.ref == 'refs/heads/develop' }}
    - run: echo "Terraform apply"
